import type { Deal, ApprovalSettings } from "@/types";

export const INIT_APPROVAL: ApprovalSettings = {
  moveToAchieved: true,
  aiMistake: true,
  manualAdd: false,
  nextAction: false,
  stageRegression: true,
};

export const INIT_DEALS: Deal[] = [
  {
    id: 1,
    company: "株式会社TechRetail",
    contact: "田中 マーケティング部長",
    products: ["AIQUA"],
    stage: "要件化",
    lastUpdate: "2日前",
    owner: "山田 太郎",
    status: "active",
    cumulativeInsight: {
      attitude: "初回は慎重・様子見だったが、2回目商談でKUが同席しデモ後に積極的に変化。部長は依然としてROI根拠を重視する姿勢。",
      preference: "定量的な数値・実績を好む。操作感のデモにも強く反応。抽象的な説明より「使ってみる体験」と「数値の根拠」の組み合わせが最も効果的。",
      tactics: "部長にはROI数値と成功事例、KUには詳細デモを継続する二段階アプローチ。IT部門接点はKU経由で自然に設定する。",
      history: [
        { date: "2026-05-10", stage: "案件化", change: "初回接触。予算・タイミングに慎重。定量エビデンスを重視する姿勢を確認。" },
        { date: "2026-05-17", stage: "要件化", change: "KU同席後に積極度が上昇。デモへの反応が良好。部長の姿勢は変わらずROI重視。" },
      ],
    },
    stageHistory: [
      { stage: "案件化", enteredAt: "2026-05-01", exitedAt: "2026-05-10" },
      { stage: "要件化", enteredAt: "2026-05-10", exitedAt: null },
    ],
    meetings: [
      {
        id: 1,
        date: "2026-05-10",
        stage: "案件化",
        type: "commercial",
        products: ["AIQUA"],
        totalScore: 19,
        maxScore: 25,
        summary: "初回商談。EC事業のメール・LINE施策改善ニーズを確認。現在b-dashを利用中で9月に契約更新。マーケティング部長（KDM）と面談。予算感は年間500万円前後。AIによるパーソナライズ強化に関心。",
        criteriaScores: [
          { id: "b1", label: "Budget", score: 4, maxScore: 5, comment: "予算感（500万円前後）は把握できたが、正式な予算承認状況が不明なため4点。", recordSummary: "田中部長より「来期の予算はマーケティング強化に充てる方針で、概ね500万円前後を想定している」との発言あり。" },
          { id: "a1", label: "Authority", score: 5, maxScore: 5, comment: "KDMであるマーケティング部長と直接面談。条件を完全に満たしている。", recordSummary: "田中部長が全商談を通じて意思決定権限を持つことを明言。「最終的には私が判断します」との発言あり。" },
          { id: "n1", label: "Need", score: 4, maxScore: 5, comment: "AIパーソナライズへの明確なニーズあり。具体的な課題の深掘りが不十分なため4点。", recordSummary: "「現在のb-dashでは一斉配信が中心で、顧客一人ひとりへのパーソナライズが全くできていない」との課題認識を確認。" },
          { id: "t1", label: "Timing", score: 4, maxScore: 5, comment: "9月の契約更新が明確。9ヶ月以内の導入可能性あり。", recordSummary: "「b-dashの契約が9月に更新を迎えるため、それまでに意思決定したい」との発言。" },
          { id: "c1", label: "Competitor", score: 2, maxScore: 5, comment: "b-dash利用中は把握できたが、不満点・比較観点の深掘りができていないため2点。", recordSummary: "「現在b-dashを使っている」との情報のみ。競合への不満や比較観点については言及なし。" },
        ],
        customerAnalysis: {
          attitude: "関心度は高いが慎重。予算・導入効果への投資対効果を重視する姿勢。",
          preference: "具体的な数値・実績を好む。定量的なエビデンスに反応。",
          tactics: "次回は競合比較の定量データとROI試算を提示。KU同席を求め、現場の具体的な課題を引き出す。",
        },
        strengths: [
          { id: "s1", text: "KDM（マーケティング部長）との接点確立", corrected: false, source: "ai" },
          { id: "s2", text: "予算感（年間500万円前後）を把握", corrected: false, source: "ai" },
          { id: "s3", text: "導入タイミング（9月契約更新）が明確", corrected: false, source: "ai" },
        ],
        gaps: [
          { id: "g1", text: "KU（主要利用者）との接点未確立", corrected: false, source: "ai" },
          { id: "g2", text: "現行b-dashへの具体的な不満点が未深掘り", corrected: false, source: "ai" },
        ],
        nextActions: [
          { id: "na1", text: "次回商談でKU（CRM担当者）の同席を依頼する", status: "active", priority: 1 },
          { id: "na2", text: "b-dashとAIQUAの比較資料を準備する", status: "active", priority: 2 },
          { id: "na3", text: "Why Appier（AIネイティブ）のメッセージを訴求する", status: "done", priority: 3 },
        ],
        corrections: [],
        managerReview: { status: "approved", comment: "基準を満たしている。KU接点確立を優先。", reviewer: "鈴木 MG", date: "2026-05-11" },
      },
      {
        id: 2,
        date: "2026-05-17",
        stage: "要件化",
        type: "commercial",
        products: ["AIQUA"],
        totalScore: 16,
        maxScore: 25,
        summary: "2回目商談（対面）。CRM担当者も同席。b-dashでは一斉配信中心でパーソナライズが進んでいない課題を確認。CVR改善とLTV向上が主要KPI。AIQUAのデモを実施し、ジャーニーコパイロットとレコメンド機能に強い反応。SDK導入状況の確認が必要。",
        criteriaScores: [
          { id: "m1", label: "Metrics", score: 4, maxScore: 5, comment: "CVR改善・LTV向上という改善KPIは確認できたが、具体的な数値目標までは未確認のため4点。", recordSummary: "田中部長「CVRを今の1.5倍にしたい」、山田氏（KU）「メールのクリック率が業界平均の半分以下で悩んでいる」との発言あり。" },
          { id: "f1_mkt", label: "Fact(AS-IS) — マーケティング施策", score: 4, maxScore: 5, comment: "b-dashでの一斉配信中心という課題は把握。KPI数値・ボトルネックの詳細が不十分。", recordSummary: "現行施策はメルマガ週1回の一斉配信のみ。セグメント配信やパーソナライズ施策は未実施。開封率は約18%とのこと。" },
          { id: "f2_sys", label: "Fact(AS-IS) — システム構成", score: 2, maxScore: 5, comment: "SDK未導入が判明したが、MA/CRM/CDP等のシステム全体構成が未把握のため2点。", recordSummary: "b-dashのみ導入。CRM・CDPは未導入。アプリあり（SDK未導入）。ECサイトはShopify。IT部門との接続が必要な状況。" },
          { id: "g1_mkt", label: "Goal(TO-BE) — マーケティング理想", score: 3, maxScore: 5, comment: "AIパーソナライズへの方向性は合意したが、具体的な顧客体験設計・理想KPI数値の合意まで至っていない。", recordSummary: "「各顧客の購買行動に合わせた1to1メッセージを実現したい」との方向性は確認。具体的なシナリオ設計は未着手。" },
          { id: "g2_sys", label: "Goal(TO-BE) — システム構想", score: 3, maxScore: 5, comment: "データ連携の方向性は示せたが、アーキテクチャの詳細合意が未完了。", recordSummary: "「ShopifyとAIQUAを連携してリアルタイムのカゴ落ちメールを実現したい」との要望あり。SDK導入やデータ連携の詳細は次回IT部門と確認予定。" },
        ],
        customerAnalysis: {
          attitude: "前回より積極的。CRM担当者（KU）はデモに強く反応。部長はまだ様子見の姿勢。",
          preference: "実際の操作感・デモを重視。抽象的な説明より「使ってみる」体験に反応が良い。",
          tactics: "IT部門を巻き込みシステム構成を明確化。部長には成功事例のROI数値、KUには詳細デモを継続する二段階アプローチ。",
        },
        strengths: [
          { id: "s4", text: "KU（CRM担当者）との接点確立", corrected: false, source: "ai" },
          { id: "s5", text: "改善対象KPI（CVR・LTV）が確認できている", corrected: false, source: "ai" },
        ],
        gaps: [
          { id: "g3", text: "現行システム構成（SDK導入状況）が未確認", corrected: false, source: "ai" },
          { id: "g4", text: "目指すアーキテクチャ・データ連携構想が未合意", corrected: false, source: "ai" },
          { id: "g5", text: "成功事例の提示が未実施", corrected: false, source: "ai" },
        ],
        nextActions: [
          { id: "na4", text: "IT部門とのシステム構成ヒアリングを設定する", status: "active", priority: 1 },
          { id: "na5", text: "同業界（アパレル・EC）の成功事例を送付する", status: "active", priority: 2 },
          { id: "na6", text: "理想のデータ連携アーキテクチャを提案資料にまとめる", status: "active", priority: 3 },
        ],
        corrections: [],
        managerReview: null,
      },
      {
        id: 3,
        date: "2026-05-19",
        stage: "要件化",
        type: "weekly_review",
        products: ["AIQUA"],
        totalScore: null,
        maxScore: null,
        summary: "週次レビュー。KUのCRM担当者が社内推進者になっている可能性あり。IT部門との接点をKU経由で作るアプローチを採用することに合意。成功事例はアパレルECを優先して送付する。次回商談は5/26を予定。",
        criteriaScores: [],
        customerAnalysis: null,
        strengths: [],
        gaps: [],
        nextActions: [
          { id: "na7", text: "KU経由でIT部門担当者を紹介してもらう", status: "active", priority: 1 },
          { id: "na8", text: "アパレルEC成功事例（CVR+18%）を今週中に送付する", status: "active", priority: 2 },
          { id: "na9", text: "次回商談（5/26）でアーキテクチャ案を提示する", status: "active", priority: 3 },
        ],
        corrections: [],
        managerReview: { status: "approved", comment: "KU活用戦略は正しい。IT部門接点を早期に。", reviewer: "鈴木 MG", date: "2026-05-19" },
        weeklyReviewData: {
          findings: [
            "KU（山田氏）が社内で積極的に推進している様子。「上司にも話してみる」との発言あり。",
            "IT部門との直接面談はハードルが高い可能性。KU経由での自然な接続が有効と判断。",
            "アパレルEC事例（CVR+18%）が顧客業界に最も近い。先行して送付することで信頼醸成を狙う。",
          ],
          agreedActions: [
            "KU経由でIT部門担当者を紹介してもらう",
            "アパレルEC成功事例（CVR+18%）を今週中に送付する",
            "次回商談（5/26）でアーキテクチャ案を提示する",
          ],
          strategyChanges: ["IT部門への直接アプローチ → KU経由での接続に変更"],
          previousReview: null,
          insightUpdate: {
            attitude: "KU（CRM担当者）が強い推進意欲を持っていることを確認。部長への働きかけが期待できる状況。",
            change: "KUの推進意欲が判明したことで、二段階アプローチの実行可能性が高まった。",
          },
        },
      },
    ],
  },
  {
    id: 2,
    company: "コスメブランドA",
    contact: "佐藤 CRM部長",
    products: ["AIRIS", "AIQUA"],
    stage: "合意化",
    lastUpdate: "1日前",
    owner: "佐藤 花子",
    status: "active",
    cumulativeInsight: {
      attitude: "案件化から一貫して積極的。合意化段階では「決断に近い」状態で、役員会での承認を最大の関門として意識。社内説得のサポートを求めている。",
      preference: "定量的なROI・競合比較データを強く重視。役員会で使いやすい資料形式（数値・比較表）への反応が最も良い。",
      tactics: "役員会資料の作成サポートを積極的に提案。DQB 40%削減などの定量証拠とTD比較表を提供。Pre-sales連携で技術的な懸念を先に解消する。",
      history: [
        { date: "2026-04-01", stage: "案件化", change: "初回から積極的。ROI根拠と競合比較を重視する姿勢を確認。" },
        { date: "2026-04-15", stage: "要件化", change: "要件定義を迅速に完了。意思決定スピードが速い顧客と判断。" },
        { date: "2026-05-15", stage: "合意化", change: "役員会承認を最終関門として意識。社内説得材料の充実を求めている。" },
      ],
    },
    stageHistory: [
      { stage: "案件化", enteredAt: "2026-04-01", exitedAt: "2026-04-15" },
      { stage: "要件化", enteredAt: "2026-04-15", exitedAt: "2026-05-05" },
      { stage: "合意化", enteredAt: "2026-05-05", exitedAt: null },
    ],
    meetings: [
      {
        id: 1,
        date: "2026-05-15",
        stage: "合意化",
        type: "commercial",
        products: ["AIRIS", "AIQUA"],
        totalScore: 20,
        maxScore: 25,
        summary: "提案資料をもとに詳細ディスカッション。ROI試算（CVR+15%想定）に納得感あり。価格提示完了。決裁は来月役員会。競合はTreasureDataと比較中。AIRISのマーケター向け操作性がTDとの差別化ポイントとして刺さっている。",
        criteriaScores: [
          { id: "sc1", label: "Scope", score: 5, maxScore: 5, comment: "要件スコープは双方で明確に合意済み。", recordSummary: "AIRIS+AIQUAのパッケージ導入、初期データ連携3ソース、フェーズ1は3ヶ月での導入という範囲で双方合意確認。" },
          { id: "roi1", label: "ROI", score: 4, maxScore: 5, comment: "CVR+15%のROI試算に納得感あり。顧客側での試算検証が未完了のため4点。", recordSummary: "提示したROI試算資料に対し「この数字は現実的だと思う」との反応。ただし「社内でも検証してみる」との発言あり。" },
          { id: "p1", label: "Price", score: 4, maxScore: 5, comment: "価格提示は完了。顧客側の正式な予算承認が未確認のため4点。", recordSummary: "年間XXX万円の提示に対し「想定範囲内」との反応。「役員会で正式承認が必要」との言及あり。" },
          { id: "dp1", label: "Decision Process", score: 4, maxScore: 5, comment: "来月役員会での稟議という流れは把握。具体的なステップが不明確。", recordSummary: "「来月15日の役員会で正式に決議する予定」との発言。承認後の手続き（発注・契約）の詳細フローは未確認。" },
          { id: "dc1", label: "Decision Criteria", score: 3, maxScore: 5, comment: "「価格とAI性能を最重視」という回答はあったが、優先順位の詳細確認が未完了。", recordSummary: "「競合のTDと比べてAIの賢さが違う、と感じている」との発言あり。価格・AI性能・サポートを重視しているとのこと。" },
        ],
        customerAnalysis: {
          attitude: "決断に近い段階。役員会という最終関門を意識しており、社内説得のサポートを求めている様子。",
          preference: "定量的なROI・競合比較データを重視。役員会向けの説得材料として使いやすい資料を好む。",
          tactics: "役員会資料の作成サポートを申し出る。AI性能の定量的証拠（DQB 40%削減）とTD比較表を提供する。",
        },
        strengths: [
          { id: "s7", text: "ROI認識合わせ完了（CVR+15%想定）", corrected: false, source: "ai" },
          { id: "s8", text: "価格提示完了", corrected: false, source: "ai" },
          { id: "s9", text: "Decision Process明確（来月役員会で稟議）", corrected: false, source: "ai" },
        ],
        gaps: [
          { id: "g6", text: "Decision Criteria（重視項目の優先順位）が未確認", corrected: false, source: "ai" },
          { id: "g7", text: "Pre-sales連携（技術QA）が未実施", corrected: false, source: "ai" },
        ],
        nextActions: [
          { id: "na10", text: "役員会資料の作成サポートを申し出る", status: "active", priority: 1 },
          { id: "na11", text: "Pre-salesと連携して技術QAを実施する", status: "active", priority: 2 },
          { id: "na12", text: "AI性能定量証拠（DQB 40%削減）を資料に追加", status: "done", priority: 3 },
        ],
        corrections: [
          { id: "c1", itemId: "g6", type: "moveToAchieved", reason: "商談後メールで「価格とAI性能を最重視、サポートも重要」と優先順位付きで回答あり。確認済みとしてよい。", date: "2026-05-15", status: "pending" },
        ],
        managerReview: null,
      },
    ],
  },
  {
    id: 3,
    company: "旅行会社B",
    contact: "山本 デジタル推進部",
    products: ["AIQUA"],
    stage: "案件化",
    lastUpdate: "12日前",
    owner: "田中 次郎",
    status: "active",
    cumulativeInsight: {
      attitude: "情報収集段階。意思決定権限を持たないインフルエンサーとの接触のみ。積極性は低く、社内への橋渡し役として動いている。",
      preference: "概要・事例を重視。機能説明より「旅行業界での具体的な活用事例」に関心を示している。",
      tactics: "まずKDM・KUへの接続が最優先。担当者に社内提案用の資料を提供し、自然な橋渡しを促す。SMCとのコスト比較が有効な切り口。",
      history: [
        { date: "2026-05-12", stage: "案件化", change: "初回接触。インフルエンサーのみ。積極性低く情報収集段階と判断。" },
      ],
    },
    stageHistory: [
      { stage: "案件化", enteredAt: "2026-05-12", exitedAt: null },
    ],
    meetings: [
      {
        id: 1,
        date: "2026-05-07",
        stage: "案件化",
        type: "commercial",
        products: ["AIQUA"],
        totalScore: 9,
        maxScore: 25,
        summary: "初回オンライン商談。デジタル推進部担当者と面談。AIマーケティングに興味あり。予算権限・タイミング不明。KDMとの接点なし。SMC利用中で大きな不満はない様子。",
        criteriaScores: [
          { id: "b1", label: "Budget", score: 1, maxScore: 5, comment: "予算の有無・金額感が全く把握できていない。担当者に予算権限がない可能性が高い。", recordSummary: "予算に関する発言は一切なし。「上の判断になる」との発言から権限がない可能性が高い。" },
          { id: "a1", label: "Authority", score: 1, maxScore: 5, comment: "インフルエンサーのみとの接点。KDM・KUとの接点が全くない状態。", recordSummary: "山本氏は「情報収集して上に報告する役割」と自己紹介。意思決定権限なし。" },
          { id: "n1", label: "Need", score: 3, maxScore: 5, comment: "AIマーケティングへの興味は確認できたが、具体的な課題・ニーズの深掘りが不十分。", recordSummary: "「AI活用に興味がある」「旅行業界でのAI活用事例を知りたい」との発言あり。具体的な課題は未確認。" },
          { id: "t1", label: "Timing", score: 2, maxScore: 5, comment: "導入タイミングが不明確。契約更新時期も未確認。", recordSummary: "「まず情報収集の段階」との発言。SMCの契約更新時期も把握できず。" },
          { id: "c1", label: "Competitor", score: 2, maxScore: 5, comment: "SMC利用中は把握できたが、不満点・比較観点が全く引き出せていない。", recordSummary: "「Salesforce Marketing Cloudを使っている」との情報のみ。特に大きな不満はないとのこと。" },
        ],
        customerAnalysis: {
          attitude: "情報収集段階。意思決定権限がなく、社内への橋渡し役として動いている可能性あり。積極性は低め。",
          preference: "まず概要理解を重視。機能説明より「どんな課題を解決できるか」を知りたがっている。",
          tactics: "KDM・KUへの接続を最優先。担当者に「社内で提案するための材料」を提供し、自然な橋渡しを促す。",
        },
        strengths: [
          { id: "s10", text: "AIマーケティングへの興味・関心あり", corrected: false, source: "ai" },
          { id: "s11", text: "競合状況（SMC利用中）把握済み", corrected: false, source: "ai" },
        ],
        gaps: [
          { id: "g8", text: "KDMとの接点なし（インフルエンサーのみ）", corrected: false, source: "ai" },
          { id: "g9", text: "予算権限・予算感が不明", corrected: false, source: "ai" },
          { id: "g10", text: "導入検討タイミングが不明確", corrected: false, source: "ai" },
        ],
        nextActions: [
          { id: "na13", text: "KDMまたはKUへの接続機会を設定する", status: "active", priority: 1 },
          { id: "na14", text: "社内提案用のWhy Appier資料を送付する", status: "active", priority: 2 },
          { id: "na15", text: "SMCとのコスト比較資料を準備する", status: "active", priority: 3 },
        ],
        corrections: [],
        managerReview: null,
      },
    ],
  },
];
